version: '3'
name: laravel-sanctum-auth
services:
    php:
        build: .docker/php
        container_name: php
        ports:
            - "5173:5173"
        volumes:
            - .:/var/www:cached
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
    db:
        image: mysql:8.1
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions

    mail:
        image: axllent/mailpit:latest
        container_name: mail
        ports:
        - "8025:8025"
        - "1025:1025"
